import { app, Menu, type NativeImage, nativeImage, Tray } from 'electron';
import menubarTemplate from '../../resources/menubarTemplate.png?asset';
import { getSettings } from './settings/conf';

let tray: Tray | null = null;

type MenuBarDeps = {
  /** Show (recreating if needed) and focus the main window. */
  showWindow: () => void;
  /** Show the window and tell the renderer to open a new chat (home). */
  newChat: () => void;
};

/** Pre-baked black+alpha template (resources/menubarTemplate.png, regenerated by
 *  scripts/gen-menubar-icon.cjs). createFromPath picks up the @2x sibling in the
 *  same dir for retina; the template flag lets macOS tint it to match the bar. */
function trayIcon(): NativeImage {
  const img = nativeImage.createFromPath(menubarTemplate);
  img.setTemplateImage(true);
  return img;
}

function buildTray(deps: MenuBarDeps): Tray {
  const t = new Tray(trayIcon());
  t.setToolTip('Atrium');
  t.setContextMenu(
    Menu.buildFromTemplate([
      { label: 'New Chat', click: deps.newChat },
      { label: 'Open Atrium', click: deps.showWindow },
      { type: 'separator' },
      // app.quit() trips before-quit, which sets isQuitting so the window's
      // hide-on-close interception steps aside and the app really exits.
      { label: 'Quit Atrium', click: () => app.quit() },
    ]),
  );
  return t;
}

function apply(enabled: boolean, deps: MenuBarDeps): void {
  if (enabled && !tray) {
    tray = buildTray(deps);
  } else if (!enabled && tray) {
    tray.destroy();
    tray = null;
  }
}

/** Mirror the menu-bar tray to the persisted setting — now, and on every toggle
 *  (electron-conf fires onDidChange when the renderer patches the scope). */
export function setupMenuBar(deps: MenuBarDeps): void {
  apply(getSettings('general.showInMenuBar'), deps);
  getSettings().onDidChange('general', (next) => {
    apply(Boolean(next?.showInMenuBar), deps);
  });
}
