import { getSettings } from '@main/settings/conf';
import { app, Menu, type NativeImage, nativeImage, Tray } from 'electron';
import menubarTemplate from '../../../resources/menubarTemplate.png?asset';
import { uiLang } from './locale';

let tray: Tray | null = null;
/** The language the current menu was built in, so a switch rebuilds it. */
let trayLang: 'en' | 'zh' | null = null;

const STRINGS = {
  en: { newChat: 'New Chat', open: 'Open Atrium', quit: 'Quit Atrium' },
  zh: { newChat: '新对话', open: '打开 Atrium', quit: '退出 Atrium' },
} as const;

type MenuBarDeps = {
  /** Show (recreating if needed) and focus the main window. */
  showWindow: () => void;
  /** Show the window and tell the renderer to open a new chat (home). */
  newChat: () => void;
};

/** Pre-baked black+alpha template (resources/menubarTemplate.png, regenerated by
 *  scripts/gen-menubar-icon.cjs). createFromPath picks up the @2x sibling in the
 *  same dir for retina; the template flag lets macOS tint it to match the bar. */
function trayIcon(): NativeImage {
  const img = nativeImage.createFromPath(menubarTemplate);
  img.setTemplateImage(true);
  return img;
}

function buildMenu(lang: 'en' | 'zh', deps: MenuBarDeps): Menu {
  const strings = STRINGS[lang];
  return Menu.buildFromTemplate([
    { label: strings.newChat, click: deps.newChat },
    { label: strings.open, click: deps.showWindow },
    { type: 'separator' },
    // app.quit() trips before-quit, which sets isQuitting so the window's
    // hide-on-close interception steps aside and the app really exits.
    { label: strings.quit, click: () => app.quit() },
  ]);
}

function apply(enabled: boolean, deps: MenuBarDeps): void {
  if (!enabled) {
    tray?.destroy();
    tray = null;
    trayLang = null;
    return;
  }
  const lang = uiLang();
  if (!tray) {
    tray = new Tray(trayIcon());
    tray.setToolTip('Atrium');
  } else if (lang === trayLang) {
    return;
  }
  tray.setContextMenu(buildMenu(lang, deps));
  trayLang = lang;
}

/** Mirror the menu-bar tray to the persisted setting — now, and on every change
 *  to the scope (electron-conf fires onDidChange when the renderer patches it).
 *  The language lives in that same scope, so a switch rebuilds the menu. */
export function setupMenuBar(deps: MenuBarDeps): void {
  apply(getSettings('general.showInMenuBar'), deps);
  getSettings().onDidChange('general', (next) => {
    apply(Boolean(next?.showInMenuBar), deps);
  });
}
